services:
  # Apache and PHP service
  web:
#    image: php:8-apache
    build: ./php
    container_name: php-apache-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  # MySQL service
  ## SET PERSIST sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: circuito
      MYSQL_USER: abasup
      MYSQL_PASSWORD: abasup
      MYSQL_ROOT_PASSWORD: abasup
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: abasup 
      MYSQL_PASSWORD: abasup
      MYSQL_ROOT_PASSWORD: abasup

# Define networks
networks:
  my-network:
